Repository mcereal/Lookin-Ruff, pull requests merged in 2020-12, with the labels that each got.

#29 admin dashboard
  config/config.json
  db/schema.sql
  db/seeds.sql
  public/admin-dashboard.html
  public/js/adminDashboard.js
  routes/api-routes.js
Labels: Size-S, enhancement

#40 routes update to get appointment info based off date
  routes/api-routes.js
Labels: Size-S, enhancement

#51 dog name and dog note saving
  models/user.js
  public/js/signup.js
  public/signup.html
  routes/api-routes.js
Labels: bugfix

#44 added temperAment files
  config/config.json
  db/schema.sql
  db/seeds.sql
  models/temperament.js
  package-lock.json
  package.json
  public/js/members.js
  public/js/signup.js
  public/members.html
  public/stylesheets/style.css
  routes/api-routes.js
Labels: Issue-Feature, Size-M, bugfix, enhancement
